[sources]

[accounts]
admin_address = "0x0000000000000000000000000000000000000000"
admin_private_key = "0x0000000000000000000000000000000000000000000000000000000000000000" # can be in the .env as well
batcher_address = "0x0000000000000000000000000000000000000000"
batcher_private_key = "0x0000000000000000000000000000000000000000000000000000000000000000" # can be in the .env as well
sequencer_address = "0x0000000000000000000000000000000000000000"
sequencer_private_key = "0x0000000000000000000000000000000000000000000000000000000000000000" # can be in the .env as well
proposer_address = "0x0000000000000000000000000000000000000000"
proposer_private_key = "0x0000000000000000000000000000000000000000000000000000000000000000" # can be in the .env as well

[network]
l1_block_time = 12
l2_block_time = 2
l2_chain_id = 11155420
max_sequencer_drift = 600
sequencer_window_size = 3600
channel_timeout = 300
p2p_sequencer_address = ""
batch_inbox_address = ""
batch_sender_address = ""
l2_output_oracle_proposer = ""
l2_output_oracle_challenger = ""
l2_output_oracle_submission_interval = 120
l2_output_oracle_starting_block_number = 0
finalization_period_seconds = ""
proxy_admin_owner = ""
base_fee_vault_recipient = ""
l1_fee_vault_recipient = ""
sequencer_fee_vault_recipient = ""
base_fee_vault_minimum_withdrawal_amount = ""
l1_fee_vault_minimum_withdrawal_amount = ""
sequencer_fee_vault_minimum_withdrawal_amount = ""
base_fee_vault_withdrawal_network = ""
l1_fee_vault_withdrawal_network = ""
sequencer_fee_vault_withdrawal_network = ""
enable_governance = ""
governance_token_symbol = ""
governance_token_name = ""
governance_token_owner = ""
l2_genesis_block_gas_limit = ""
l2_genesis_block_base_fee_per_gas = ""
eip1559_denominator = ""
eip1559_elasticity = ""
l2_genesis_regolith_time_offset = ""
system_config_start_block = ""
required_protocol_version = ""
recommended_protocol_version = ""
fund_dev_accounts = ""
fault_game_absolute_prestate = ""
fault_game_max_depth = ""
fault_game_clock_extension = ""
fault_game_max_clock_duration = ""
fault_game_genesis_block = ""
fault_game_genesis_output_root = ""
fault_game_split_depth = ""
fault_game_withdrawal_delay = ""
preimage_oracle_min_proposal_size = ""
preimage_oracle_challenge_period = ""
proof_maturity_delay_seconds = ""
dispute_game_finality_delay_seconds = ""
respected_game_type = ""
use_fault_proofs = ""
