apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.demo.deployment.name }}
  labels:
    app: {{ .Values.demo.deployment.appLabel }}
spec:
  replicas: {{ .Values.demo.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.demo.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.demo.deployment.appLabel }}
    spec:
      containers:
        - name: {{ .Values.demo.deployment.containerName }}
          image: "{{ .Values.demo.deployment.image.repository }}:{{ .Values.demo.deployment.image.tag }}"
          ports:
            - containerPort: {{ .Values.demo.deployment.containerPort }}