
global:
  storageClassName: gp2 # Override with "" for default (recommended in local environment)
  image:
    pullPolicy: IfNotPresent

blockscout:
  postgres:
    dbName: blockscout-db
    user: user
    password: password
    image:
      repository: postgres
      tag: latest
    storage: 5Gi

blockscout-stack:
  config:
    prometheus:
      enabled: false
  blockscout:
    ingress:
      enabled: true
      className: nginx
      hostname: self.global.host

    env:
      CHAIN_ID: self.chain.id TODO:
      NETWORK: "Optimism"
      ECTO_USE_SSL: "false"
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_HTTP_URL: self.proxyd.urls.http
      ETHEREUM_JSONRPC_WS_URL: self.proxyd.urls.ws
    extraEnv:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: blockscout-secret
            key: DATABASE_URL
            
  frontend:
    ingress:
      enabled: true
      className: nginx
      hostname: self.global.host
    env:
      NEXT_PUBLIC_API_PROTOCOL: self.global.protocol
