apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # Iterate over the host array to determine if any host is not "localhost" for cert-manager
    {{- $needsCert := false }}
    {{- range .Values.global.hosts }}
    {{- if ne . "localhost" }}
    {{- $needsCert = true }}
    {{- end }}
    {{- end }}
    {{- if $needsCert }}
    cert-manager.io/issuer: "letsencrypt"  # TLS requirement - enables cert-manager
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  # TLS configuration for all non-localhost hosts
  {{- $tlsHosts := list }}
  {{- range .Values.global.hosts }}
  {{- if ne . "localhost" }}
  {{- $tlsHosts = append $tlsHosts . }}
  {{- end }}
  {{- end }}
  {{- if $tlsHosts }}
  tls:
    {{- range $tlsHosts }}
    - hosts:
        - {{ . }}
      secretName: {{ . | replace "." "-" }}-tls  # TLS requirement - certificate stored here
    {{- end }}
  {{- end }}
  rules:
    # Generate a rule for each host in the array
    {{- range .Values.global.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.proxyd.ingress.nodePath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.proxyd.name }}-service
                port:
                  number: {{ $.Values.proxyd.port }}
    {{- end }}
